export const SENSITIVE_PATHS = [
  { path: '/.env', severity: 'CRITICAL' },
  { path: '/.env.local', severity: 'CRITICAL' },
  { path: '/.env.production', severity: 'CRITICAL' },
  { path: '/.env.prod', severity: 'CRITICAL' },
  { path: '/.git/config', severity: 'CRITICAL' },
  { path: '/.git/HEAD', severity: 'HIGH' },
  { path: '/config.json', severity: 'HIGH' },
  { path: '/package.json', severity: 'MEDIUM' },
  { path: '/.DS_Store', severity: 'LOW' },
  { path: '/.htaccess', severity: 'MEDIUM' },
  { path: '/phpinfo.php', severity: 'HIGH' },
  { path: '/_profiler', severity: 'HIGH' },
  { path: '/_wdt', severity: 'HIGH' },
  { path: '/api/', severity: 'MEDIUM' },
  { path: '/admin', severity: 'MEDIUM' },
  { path: '/graphql', severity: 'MEDIUM' },
  { path: '/debug', severity: 'MEDIUM' },
  { path: '/.well-known/', severity: 'LOW' },
];
